### ISSUE TITLE
I'm trying

### ISSUE THREAD

**Issue by Loupoulou** [LifetimeMistake/PlanetbaseMultiplayer#2]
Hi, I've been trying for 3 days to install this mod because I want to play to planetbase with my friends but I can figure out how it works and I don't understand how to do download it so I can't play with this mod.
Can you help me ? 
Thank you.

**Comment by LifetimeMistake** [comment]
Hi Loupoulou, unfortunately I stopped working on this project a while ago and left it in an unfinished state. While it is technically possible to play online using this mod, you will encounter a number of issues hours (if not minutes) into the game. 

This is because some very important features are not yet implemented, including game features (for example trader ships won't arrive at the same time for both players) and some mod features such as desync handling and correction (for example making sure that no conflicts about the game state arise). This means opting out of the unfinished features or risking breaking your save / crashing the game.

There is no standard way to install the mod either. Currently, it relies on manually patching some of the game's code to make it work. If you do still want to give it a try though, you should read the "Setting up a development environment" section of the readme. You will need to compile the mod from source so make sure you have Visual Studio with tools for targeting the .NET framework 3.5. 

Please note that the mod has not been touched for more than a year and any updates by the Planetbase developers could have broken this project. You should back up your save data and/or game before proceeding to install any modifications.

Cheers.

**Comment by Loupoulou** [comment]
Thank you for the answer. I hope you will one day work again on this project.
Have a good day.
